version: 2.1

executors:
  ruby-2-7:
    resource_class: small
    docker:
      - image: cimg/ruby:2.7
        environment:
          BUNDLE_VERSION: "~> 2.3"

# yaml anchor filters
master_only: &master_only
  filters:
    branches:
      only: master
    tags:
      ignore: /.*/
pr_only: &pr_only
  filters:
    branches:
      ignore: master
    tags:
      ignore: /.*/
version_tags_only: &version_tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

jobs:
  build:
    executor: ruby-2-7
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            gem install bundler --version "${BUNDLE_VERSION}" --force
            bundle config set --local jobs '4'
            bundle config set --local retry '3'
            bundle install --local
      - run:
          name: Build documentation
          command: bundle exec rake ci:doc
      - store_artifacts:
          name: Saves documentation
          path: doc

  future_version_multivariant:
    parameters:
      ruby-version:
        type: string
    resource_class: small
    description: "Rb << parameters.ruby-version >>"
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
        environment:
          BUNDLE_VERSION: "2.3.17"
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            gem install bundler --version "${BUNDLE_VERSION}" --force
            bundle config set --local jobs '4'
            bundle config set --local retry '3'
      - run:
          name: Local Bundle Install
          command: bundle install --local
      - run:
          name: Run Tests
          command: ruby -v && bundle exec rake ci:specs
      - store_test_results:
          name: Store test results
          path: tmp/test-results

workflows:
  version: 2

  trunk:
    jobs:
      - build:
          <<: *master_only

  pull-requests:
    jobs:
      - future_version_multivariant:
          <<: *pr_only
          name: "Rb << matrix.ruby-version >>"
          context: nexus_readonly
          matrix:
            parameters:
              ruby-version: [ "2.7.6", "3.0.3", "3.1.2" ]
      - build:
          <<: *pr_only

  final-release:
    jobs:
      - build:
          <<: *version_tags_only
