#!/usr/bin/env ruby
# vi: ft=ruby

require "bundler/setup"
require "oauth2/client"

include OAuth2::Client

STDOUT.sync = true

options = CLI::Options.new(
  strategy: "authorization_code",
)
CLI.new(options).run!(ARGV)
